<?php
/**
 * V3 CPT Custom Fields Settings for GeoDirectory
 *
 * This configuration file defines the structure and available field
 * types for the custom field form builder.
 *
 * @package     GeoDirectory
 * @since       3.0.0
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Import our new factory class to build the field settings.
use AyeCode\GeoDirectory\Admin\Utils\FormFieldFactory;

return [
	'id'    => 'fields_form_builder',
	'name'  => __( 'Fields', 'geodirectory' ),
	'icon'  => 'fa-solid fa-bars',
	'type'  => 'form_builder',
	'templates' => [
		[
			'group_title' => __( 'Standard Fields', 'geodirectory' ),
			'options' => [
				[
					'title'   => __( 'Text', 'geodirectory' ),
					'icon'    => 'fas fa-minus',
					'fields'  => FormFieldFactory::build([
						'type'           => [ 'default' => 'text' ],
						'admin_title'    => [ 'default' => 'New Text Field' ],
						'frontend_title' => [ 'default' => 'New Text Field' ],
						'htmlvar_name',
						'field_icon',
						'frontend_desc',
						'placeholder',
						'default_value',
						'is_required',
						'required_msg',
						'is_active',
						'for_admin_use',
						'show_in',
						'css_class',
						'cat_sort',
					]),
				],
				[
					'title'   => __( 'Textarea', 'geodirectory' ),
					'icon'    => 'fas fa-bars',
					'fields'  => FormFieldFactory::build([
						'type'           => [ 'default' => 'textarea' ],
						'admin_title'    => [ 'default' => 'New Textarea' ],
						'frontend_title' => [ 'default' => 'New Textarea' ],
						'htmlvar_name',
						'field_icon',
						'frontend_desc',
						'default_value',
						'is_required',
						'required_msg',
						'is_active',
						'for_admin_use',
						'show_in',
						'css_class',
					]),
				],
				[
					'title'   => __( 'Select', 'geodirectory' ),
					'icon'    => 'fas fa-caret-square-down',
					'fields'  => FormFieldFactory::build([
						'type'           => [ 'default' => 'select' ],
						'admin_title'    => [ 'default' => 'New Select' ],
						'frontend_title' => [ 'default' => 'New Select' ],
						'htmlvar_name',
						'field_icon',
						'frontend_desc',
						'options'        => [ 'default' => "option_1 : Option 1\noption_2 : Option 2" ],
						'default_value',
						'is_required',
						'required_msg',
						'is_active',
						'for_admin_use',
						'show_in',
						'css_class',
						'cat_sort',
					]),
				],
				[
					'title'   => __( 'Multiselect', 'geodirectory' ),
					'icon'    => 'fas fa-caret-square-down',
					'fields'  => FormFieldFactory::build([
						'type'           => [ 'default' => 'multiselect' ],
						'admin_title'    => [ 'default' => 'New Multiselect' ],
						'frontend_title' => [ 'default' => 'New Multiselect' ],
						'htmlvar_name',
						'field_icon',
						'frontend_desc',
						'options'        => [ 'default' => "option_1 : Option 1\noption_2 : Option 2" ],
						'default_value',
						'is_required',
						'required_msg',
						'is_active',
						'for_admin_use',
						'show_in',
						'css_class',
						'cat_sort',
					]),
				],
				[
					'title'   => __( 'Checkbox', 'geodirectory' ),
					'icon'    => 'fas fa-check-square',
					'fields'  => FormFieldFactory::build([
						'type'           => [ 'default' => 'checkbox' ],
						'admin_title'    => [ 'default' => 'New Checkbox' ],
						'frontend_title' => [ 'default' => 'New Checkbox' ],
						'htmlvar_name',
						'field_icon',
						'frontend_desc',
						'default_value'  => [ 'description' => __( 'Should this be checked by default? Use 1 for checked, 0 for unchecked.', 'geodirectory' ) ],
						'is_active',
						'for_admin_use',
						'show_in',
						'css_class',
						'cat_sort',
					]),
				],
				[
					'title'   => __( 'Radio', 'geodirectory' ),
					'icon'    => 'far fa-dot-circle',
					'fields'  => FormFieldFactory::build([
						'type'           => [ 'default' => 'radio' ],
						'admin_title'    => [ 'default' => 'New Radio Buttons' ],
						'frontend_title' => [ 'default' => 'New Radio Buttons' ],
						'htmlvar_name',
						'field_icon',
						'frontend_desc',
						'options'        => [ 'default' => "option_1 : Option 1\noption_2 : Option 2" ],
						'default_value',
						'is_required',
						'required_msg',
						'is_active',
						'for_admin_use',
						'show_in',
						'css_class',
						'cat_sort',
					]),
				],
				[
					'title'   => __( 'Email', 'geodirectory' ),
					'icon'    => 'far fa-envelope',
					'fields'  => FormFieldFactory::build([
						'type'           => [ 'default' => 'email' ],
						'admin_title'    => [ 'default' => 'New Email Field' ],
						'frontend_title' => [ 'default' => 'Email Address' ],
						'htmlvar_name',
						'field_icon'     => [ 'default' => 'fas fa-envelope' ],
						'frontend_desc',
						'placeholder',
						'default_value',
						'is_required',
						'required_msg',
						'is_active',
						'for_admin_use',
						'show_in',
						'css_class',
					]),
				],
				[
					'title'   => __( 'Phone', 'geodirectory' ),
					'icon'    => 'fas fa-phone',
					'fields'  => FormFieldFactory::build([
						'type'           => [ 'default' => 'phone' ],
						'admin_title'    => [ 'default' => 'New Phone Field' ],
						'frontend_title' => [ 'default' => 'Phone Number' ],
						'htmlvar_name',
						'field_icon'     => [ 'default' => 'fas fa-phone' ],
						'frontend_desc',
						'placeholder',
						'default_value',
						'is_required',
						'required_msg',
						'is_active',
						'for_admin_use',
						'show_in',
						'css_class',
					]),
				],
				[
					'title'   => __( 'URL', 'geodirectory' ),
					'icon'    => 'fas fa-link',
					'fields'  => FormFieldFactory::build([
						'type'           => [ 'default' => 'url' ],
						'admin_title'    => [ 'default' => 'New URL Field' ],
						'frontend_title' => [ 'default' => 'Website' ],
						'htmlvar_name',
						'field_icon'     => [ 'default' => 'fas fa-globe' ],
						'frontend_desc',
						'placeholder',
						'default_value',
						'is_required',
						'required_msg',
						'is_active',
						'for_admin_use',
						'show_in',
						'css_class',
					]),
				],
				[
					'title'   => __( 'Date', 'geodirectory' ),
					'icon'    => 'fas fa-calendar',
					'fields'  => FormFieldFactory::build([
						'type'           => [ 'default' => 'datepicker' ],
						'admin_title'    => [ 'default' => 'New Date Field' ],
						'frontend_title' => [ 'default' => 'New Date Field' ],
						'htmlvar_name',
						'field_icon',
						'frontend_desc',
						'default_value',
						'is_required',
						'required_msg',
						'is_active',
						'for_admin_use',
						'show_in',
						'css_class',
						'cat_sort',
					]),
				],
				[
					'title'   => __( 'Time', 'geodirectory' ),
					'icon'    => 'fas fa-clock',
					'fields'  => FormFieldFactory::build([
						'type'           => [ 'default' => 'time' ],
						'admin_title'    => [ 'default' => 'New Time Field' ],
						'frontend_title' => [ 'default' => 'New Time Field' ],
						'htmlvar_name',
						'field_icon',
						'frontend_desc',
						'default_value',
						'is_required',
						'required_msg',
						'is_active',
						'for_admin_use',
						'show_in',
						'css_class',
						'cat_sort',
					]),
				],
				[
					'title'   => __( 'HTML', 'geodirectory' ),
					'icon'    => 'fas fa-code',
					'fields'  => FormFieldFactory::build([
						'type'           => [ 'default' => 'html' ],
						'admin_title'    => [ 'default' => 'New HTML Block' ],
						'frontend_title' => [ 'default' => 'New HTML Block' ],
						'htmlvar_name',
						'frontend_desc',
						'default_value',
						'is_active',
						'for_admin_use',
						'show_in',
					]),
				],
				[
					'title'   => __( 'File Upload', 'geodirectory' ),
					'icon'    => 'far fa-file',
					'fields'  => FormFieldFactory::build([
						'type'           => [ 'default' => 'file' ],
						'admin_title'    => [ 'default' => 'New File Upload' ],
						'frontend_title' => [ 'default' => 'New File Upload' ],
						'htmlvar_name',
						'field_icon',
						'frontend_desc',
						'is_required',
						'required_msg',
						'is_active',
						'for_admin_use',
						'show_in',
						'css_class',
					]),
				],
			]
		],
	]
];
