<?php
/**
 * GeoDirectory BlockStrap Features
 *
 * @author   AyeCode
 * @category Full Site Editing
 * @package  GeoDirectory
 * @since    2.0.x
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class GeoDir_BlockStrap {


	public static function init() {
		add_filter( 'blockstrap_pattern_page_content_gd_archive_default', array( __CLASS__, 'archive_template' ), 10, 1 );
		add_filter( 'blockstrap_pattern_page_content_gd_search_default', array( __CLASS__, 'search_template' ), 10, 1 );
		add_filter( 'blockstrap_pattern_page_content_gd_single_default', array( __CLASS__, 'single_template' ), 10, 1 );

	}

	/**
	 * Add content to the GD singlee page template of the BLockStrap theme.
	 *
	 * @param $content
	 *
	 * @return string
	 */
	public static function single_template( $content ) {
		return '<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-color","bg_color":"rgba(0,0,0,0.53)","bg_gradient":"linear-gradient(135deg,rgb(7,101,155) 1%,rgba(155,81,224,0.49) 100%)","bg_image_use_featured":true,"bg_image":"http://localhost/wp-content/uploads/2022/09/ebbdaae8-f6c3-3f98-b210-6372aacc480f.jpg","bg_image_id":2630,"bg_image_xy":{"x":0.5,"y":0.48},"text_color":"white","text_align_lg":"text-lg-center","pt_lg":"5","pb_lg":"5","position":"position-relative","className":"block-1618467995"} -->
[bs_container container=\'container-fluid\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'custom-color\'  bg_color=\'rgba(0,0,0,0.53)\'  bg_gradient=\'linear-gradient(135deg,rgb(7,101,155) 1%,rgba(155,81,224,0.49) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'true\'  bg_image=\'http://localhost/wp-content/uploads/2022/09/ebbdaae8-f6c3-3f98-b210-6372aacc480f.jpg\'  bg_image_id=\'2630\'  bg_image_xy=\'{x:0.5,y:0.48}\'  bg_on_text=\'false\'  text_color=\'white\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'text-lg-center\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'5\'  pr_lg=\'\'  pb_lg=\'5\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'position-relative\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 pt-5 pb-5 bg-custom-color text-white text-center container-fluid position-relative" style="background-color:rgba(0,0,0,0.53);background-image:url(http://localhost/wp-content/plugins/geodirectory/vendor/ayecode/wp-super-duper/icons/placeholder.png);background-blend-mode:overlay;background-size:cover;background-position:50% 48%"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","bg_image_xy":{"x":0.47,"y":0.45},"pt_lg":"5","pb_lg":"5","className":"block-1618467995"} -->
	[bs_container container=\'row\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:0.47,y:0.45}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'5\'  pr_lg=\'\'  pb_lg=\'5\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 pt-5 pb-5 row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","pt_lg":"5","pb_lg":"5","className":"block-1618467995"} -->
		[bs_container container=\'col\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'5\'  pr_lg=\'\'  pb_lg=\'5\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 pt-5 pb-5 col"><!-- wp:post-title {"textColor":"light-grey","className":"is-style-default","fontSize":"extra-large"} /-->

			<!-- wp:geodirectory/geodir-widget-post-meta {"show_advanced":true,"key":"phone","content":""} -->
			[gd_post_meta title=\'\'  id=\'\'  key=\'phone\'  show=\'\'  no_wrap=\'false\'  alignment=\'\'  text_alignment=\'\'  list_hide=\'\'  list_hide_secondary=\'\'  location=\'\'  css_class=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\' ]
			<!-- /wp:geodirectory/geodir-widget-post-meta --></div>[/bs_container]
		<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
	<!-- /wp:blockstrap/blockstrap-widget-container -->

	<!-- wp:blockstrap/blockstrap-widget-shape-divider {"sd":"curve","sd_position":"bottom","sd_color":"white","sd_invert":true,"styleid":"block-w80hp7z414"} -->
	[bs_shape_divider sd=\'curve\'  sd_position=\'bottom\'  sd_color=\'white\'  sd_custom_color=\'#0073aa\'  sd_width=\'200\'  sd_height=\'100\'  sd_flip=\'false\'  sd_invert=\'true\'  sd_btf=\'false\'  styleid=\'block-w80hp7z414\' ]<div class="wp-block-blockstrap-blockstrap-widget-shape-divider block-w80hp7z414 blockstrap-shape blockstrap-shape-bottom position-absolute"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 100" preserveAspectRatio="none">	<path class="bg-white blockstrap-shape-fill" d="M500,97C126.7,96.3,0.8,19.8,0,0v100l1000,0V1C1000,19.4,873.3,97.8,500,97z"/></svg></div><style>.block-w80hp7z414 { pointer-events: none;background-repeat: no-repeat;bottom:  -1px; left: -1px;right: -1px;line-height: 0;overflow: hidden;}.block-w80hp7z414 svg{ height: 100px;width: calc(200% + 1.3px);left: 50%;position: relative;display: block;-webkit-transform: translateX(-50%); -ms-transform: translateX(-50%); transform: translateX(-50%);}.block-w80hp7z414 svg path{ }</style>[/bs_shape_divider]
	<!-- /wp:blockstrap/blockstrap-widget-shape-divider --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-sm","bg_color":"rgba(255,255,255,0.23)","mt_lg":"5","mb_lg":"5","pt_lg":"3","rounded_size":"sm","anchor":"main","className":"block-1618467995"} -->
[bs_container container=\'container-sm\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'rgba(255,255,255,0.23)\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'5\'  mr_lg=\'\'  mb_lg=\'5\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'3\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'sm\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'main\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mt-5 mb-lg-5 pt-3 rounded-sm container-sm" id="main"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","className":"block-1618467995"} -->
	[bs_container container=\'row\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_lg":"8","className":"block-1618467995"} -->
		[bs_container container=\'col\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'8\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 col-8 col"><!-- wp:geodirectory/geodir-widget-notifications -->
			<div class="wp-block-geodirectory-geodir-widget-notifications">[gd_notifications]</div>
			<!-- /wp:geodirectory/geodir-widget-notifications -->

			<!-- wp:geodirectory/geodir-widget-single-tabs {"show_advanced":true,"content":""} -->
			<div class="wp-block-geodirectory-geodir-widget-single-tabs">[gd_single_tabs show_as_list=\'false\'  output=\'\'  tab_style=\'\'  disable_greedy=\'false\' ]</div>
			<!-- /wp:geodirectory/geodir-widget-single-tabs --></div>[/bs_container]
		<!-- /wp:blockstrap/blockstrap-widget-container -->

		<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","className":"block-1618467995"} -->
		[bs_container container=\'col\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 col"><!-- wp:blockstrap/blockstrap-widget-container {"container":"list-group","text_color":"dark","mb_lg":"","shadow":"shadow","position":"sticky-top","sticky_offset_top":115,"className":"block-1618467995"} -->
			[bs_container container=\'list-group\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'dark\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'shadow\'  position=\'sticky-top\'  sticky_offset_top=\'115\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 text-dark list-group sticky-top shadow" style="top:115px"><!-- wp:blockstrap/blockstrap-widget-container {"container":"list-group-item","mb_lg":"","className":"block-1618467995"} -->
				[bs_container container=\'list-group-item\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 list-group-item"><!-- wp:geodirectory/geodir-widget-post-meta {"key":"post_tags","content":""} -->
					[gd_post_meta title=\'\'  id=\'\'  key=\'post_tags\'  show=\'\'  no_wrap=\'false\'  alignment=\'\'  text_alignment=\'\'  list_hide=\'\'  list_hide_secondary=\'\'  location=\'\'  css_class=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\' ]
					<!-- /wp:geodirectory/geodir-widget-post-meta --></div>[/bs_container]
				<!-- /wp:blockstrap/blockstrap-widget-container -->

				<!-- wp:blockstrap/blockstrap-widget-container {"container":"list-group-item","mb_lg":"","className":"block-1618467995"} -->
				[bs_container container=\'list-group-item\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 list-group-item"><!-- wp:geodirectory/geodir-widget-post-meta {"key":"post_category","content":""} -->
					[gd_post_meta title=\'\'  id=\'\'  key=\'post_category\'  show=\'\'  no_wrap=\'false\'  alignment=\'\'  text_alignment=\'\'  list_hide=\'\'  list_hide_secondary=\'\'  location=\'\'  css_class=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\' ]
					<!-- /wp:geodirectory/geodir-widget-post-meta --></div>[/bs_container]
				<!-- /wp:blockstrap/blockstrap-widget-container -->

				<!-- wp:blockstrap/blockstrap-widget-container {"container":"list-group-item","mb_lg":"","className":"block-1618467995"} -->
				[bs_container container=\'list-group-item\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 list-group-item"><!-- wp:geodirectory/geodir-widget-post-meta {"key":"address","content":""} -->
					[gd_post_meta title=\'\'  id=\'\'  key=\'address\'  show=\'\'  no_wrap=\'false\'  alignment=\'\'  text_alignment=\'\'  list_hide=\'\'  list_hide_secondary=\'\'  location=\'\'  css_class=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\' ]
					<!-- /wp:geodirectory/geodir-widget-post-meta --></div>[/bs_container]
				<!-- /wp:blockstrap/blockstrap-widget-container -->

				<!-- wp:blockstrap/blockstrap-widget-container {"container":"list-group-item","mb_lg":"","className":"block-1618467995"} -->
				[bs_container container=\'list-group-item\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 list-group-item"><!-- wp:geodirectory/geodir-widget-post-meta {"key":"phone","content":""} -->
					[gd_post_meta title=\'\'  id=\'\'  key=\'phone\'  show=\'\'  no_wrap=\'false\'  alignment=\'\'  text_alignment=\'\'  list_hide=\'\'  list_hide_secondary=\'\'  location=\'\'  css_class=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\' ]
					<!-- /wp:geodirectory/geodir-widget-post-meta --></div>[/bs_container]
				<!-- /wp:blockstrap/blockstrap-widget-container -->

				<!-- wp:blockstrap/blockstrap-widget-container {"container":"list-group-item","mb_lg":"","className":"block-1618467995"} -->
				[bs_container container=\'list-group-item\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 list-group-item"><!-- wp:geodirectory/geodir-widget-post-meta {"key":"email","content":""} -->
					[gd_post_meta title=\'\'  id=\'\'  key=\'email\'  show=\'\'  no_wrap=\'false\'  alignment=\'\'  text_alignment=\'\'  list_hide=\'\'  list_hide_secondary=\'\'  location=\'\'  css_class=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\' ]
					<!-- /wp:geodirectory/geodir-widget-post-meta --></div>[/bs_container]
				<!-- /wp:blockstrap/blockstrap-widget-container -->

				<!-- wp:blockstrap/blockstrap-widget-container {"container":"list-group-item","mb_lg":"","className":"block-1618467995"} -->
				[bs_container container=\'list-group-item\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 list-group-item"><!-- wp:geodirectory/geodir-widget-post-meta {"key":"website","content":""} -->
					[gd_post_meta title=\'\'  id=\'\'  key=\'website\'  show=\'\'  no_wrap=\'false\'  alignment=\'\'  text_alignment=\'\'  list_hide=\'\'  list_hide_secondary=\'\'  location=\'\'  css_class=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\' ]
					<!-- /wp:geodirectory/geodir-widget-post-meta --></div>[/bs_container]
				<!-- /wp:blockstrap/blockstrap-widget-container -->

				<!-- wp:blockstrap/blockstrap-widget-container {"container":"list-group-item","mb_lg":"","className":"block-1618467995"} -->
				[bs_container container=\'list-group-item\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 list-group-item"><!-- wp:geodirectory/geodir-widget-post-meta {"key":"twitter","content":""} -->
					[gd_post_meta title=\'\'  id=\'\'  key=\'twitter\'  show=\'\'  no_wrap=\'false\'  alignment=\'\'  text_alignment=\'\'  list_hide=\'\'  list_hide_secondary=\'\'  location=\'\'  css_class=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\' ]
					<!-- /wp:geodirectory/geodir-widget-post-meta --></div>[/bs_container]
				<!-- /wp:blockstrap/blockstrap-widget-container -->

				<!-- wp:blockstrap/blockstrap-widget-container {"container":"list-group-item","mb_lg":"","className":"block-1618467995"} -->
				[bs_container container=\'list-group-item\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 list-group-item"><!-- wp:geodirectory/geodir-widget-post-meta {"key":"facebook","content":""} -->
					[gd_post_meta title=\'\'  id=\'\'  key=\'facebook\'  show=\'\'  no_wrap=\'false\'  alignment=\'\'  text_alignment=\'\'  list_hide=\'\'  list_hide_secondary=\'\'  location=\'\'  css_class=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\' ]
					<!-- /wp:geodirectory/geodir-widget-post-meta --></div>[/bs_container]
				<!-- /wp:blockstrap/blockstrap-widget-container -->

				<!-- wp:blockstrap/blockstrap-widget-container {"container":"list-group-item","mb_lg":"","className":"block-1618467995"} -->
				[bs_container container=\'list-group-item\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 list-group-item"><!-- wp:geodirectory/geodir-widget-post-meta {"key":"business_hours","content":""} -->
					[gd_post_meta title=\'\'  id=\'\'  key=\'business_hours\'  show=\'\'  no_wrap=\'false\'  alignment=\'\'  text_alignment=\'\'  list_hide=\'\'  list_hide_secondary=\'\'  location=\'\'  css_class=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\' ]
					<!-- /wp:geodirectory/geodir-widget-post-meta --></div>[/bs_container]
				<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
			<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
		<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
	<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-color","bg_color":"#f5f9fe","mt_lg":"5","mb_lg":"","pt_lg":"5","pb_lg":"5","className":"block-1618467995"} -->
[bs_container container=\'container-fluid\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'custom-color\'  bg_color=\'#f5f9fe\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'5\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'5\'  pr_lg=\'\'  pb_lg=\'5\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mt-5 pt-5 pb-5 bg-custom-color container-fluid" style="background-color:#f5f9fe"><!-- wp:blockstrap/blockstrap-widget-container {"text_color":"dark","mb_lg":"","pt_lg":"5","pb_lg":"5","display":"d-none","display_lg":"d-lg-block","className":"block-1618467995"} -->
	[bs_container container=\'container\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'dark\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'5\'  pr_lg=\'\'  pb_lg=\'5\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'d-none\'  display_md=\'\'  display_lg=\'d-lg-block\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 pt-5 pb-5 text-dark d-none d-lg-block container"><!-- wp:heading {"style":{"spacing":{"margin":{"bottom":"60px"}}},"textColor":"gray-dark"} -->
		<h2 class="has-gray-dark-color has-text-color" style="margin-bottom:60px">Similar places</h2>
		<!-- /wp:heading -->

		<!-- wp:geodirectory/geodir-widget-listings {"show_advanced":true,"related_to":"category","post_limit":3,"layout":"3","view_all_link":false,"hide_if_empty":true,"content":""} -->
		<div class="wp-block-geodirectory-geodir-widget-listings">[gd_listings title=\'\'  post_type=\'gd_place\'  category=\'\'  event_type=\'\'  single_event=\'false\'  related_to=\'category\'  tags=\'\'  post_author=\'\'  post_limit=\'3\'  post_ids=\'\'  add_location_filter=\'true\'  nearby_gps=\'false\'  show_featured_only=\'false\'  show_special_only=\'false\'  with_pics_only=\'false\'  with_videos_only=\'false\'  show_favorites_only=\'false\'  favorites_by_user=\'\'  use_viewing_post_type=\'false\'  use_viewing_term=\'false\'  sort_by=\'\'  title_tag=\'h3\'  layout=\'3\'  view_all_link=\'false\'  with_pagination=\'false\'  top_pagination=\'false\'  bottom_pagination=\'true\'  pagination_info=\'\'  hide_if_empty=\'true\'  row_gap=\'\'  column_gap=\'\'  card_border=\'\'  card_shadow=\'\'  bg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  with_carousel=\'\'  with_indicators=\'\'  with_controls=\'\'  slide_interval=\'5\'  slide_ride=\'\' ]</div>
		<!-- /wp:geodirectory/geodir-widget-listings --></div>[/bs_container]
	<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"light","mb_lg":"","shadow":"shadow","position":"fixed-bottom","display":"d-block","display_md":"d-md-none","display_lg":"d-lg-none"} -->
[bs_container container=\'container-fluid\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'light\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'shadow\'  position=\'fixed-bottom\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'d-block\'  display_md=\'d-md-none\'  display_lg=\'d-lg-none\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 bg-light d-block d-md-none d-lg-none container-fluid fixed-bottom shadow"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","text_color":"dark","text_align_lg":"text-lg-center","mb_lg":""} -->
	[bs_container container=\'row\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'dark\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'text-lg-center\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 text-dark text-center row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_lg":""} -->
		[bs_container container=\'col\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 col"><!-- wp:geodirectory/geodir-widget-post-badge {"key":"phone","condition":"is_not_empty","icon_class":"fas fa-phone","badge":" ","link":"%%input%%","new_window":true,"bg_color":"#ffffff00","txt_color":"#8500f9","size":"h1","content":""} -->
			[gd_post_badge id=\'\'  key=\'phone\'  condition=\'is_not_empty\'  search=\'\'  icon_class=\'fas fa-phone\'  badge=\' \'  link=\'%%input%%\'  new_window=\'true\'  popover_title=\'\'  popover_text=\'\'  cta=\'\'  tooltip_text=\'\'  hover_content=\'\'  hover_icon=\'\'  type=\'\'  shadow=\'\'  color=\'\'  bg_color=\'#ffffff00\'  txt_color=\'#8500f9\'  size=\'h1\'  alignment=\'\'  position=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  list_hide=\'\'  list_hide_secondary=\'\'  css_class=\'\' ]
			<!-- /wp:geodirectory/geodir-widget-post-badge --></div>[/bs_container]
		<!-- /wp:blockstrap/blockstrap-widget-container -->

		<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_lg":"","border":"0"} -->
		[bs_container container=\'col\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'0\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 border-0 col"><!-- wp:geodirectory/geodir-widget-post-badge {"key":"website","condition":"is_not_empty","icon_class":"fas fa-globe","badge":" ","link":"%%input%%","new_window":true,"bg_color":"#ffffff00","txt_color":"#8500f9","size":"h1","content":""} -->
			[gd_post_badge id=\'\'  key=\'website\'  condition=\'is_not_empty\'  search=\'\'  icon_class=\'fas fa-globe\'  badge=\' \'  link=\'%%input%%\'  new_window=\'true\'  popover_title=\'\'  popover_text=\'\'  cta=\'\'  tooltip_text=\'\'  hover_content=\'\'  hover_icon=\'\'  type=\'\'  shadow=\'\'  color=\'\'  bg_color=\'#ffffff00\'  txt_color=\'#8500f9\'  size=\'h1\'  alignment=\'\'  position=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  list_hide=\'\'  list_hide_secondary=\'\'  css_class=\'\' ]
			<!-- /wp:geodirectory/geodir-widget-post-badge --></div>[/bs_container]
		<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
	<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->';
	}

	/**
	 * Add content to the GD search page template of the BLockStrap theme.
	 *
	 * @param $content
	 *
	 * @return string
	 */
	public static function search_template( $content ) {
		return '<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-gradient","bg_gradient":"linear-gradient(135deg,rgb(2,11,185) 2%,rgb(126,5,170) 100%)","position":"position-relative"} -->
[bs_container container=\'container-fluid\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'custom-gradient\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgb(2,11,185) 2%,rgb(126,5,170) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'position-relative\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 bg-custom-gradient container-fluid position-relative" style="background-image:linear-gradient(135deg,rgb(2,11,185) 2%,rgb(126,5,170) 100%)"><!-- wp:blockstrap/blockstrap-widget-shape-divider {"sd":"curve","sd_position":"bottom","sd_color":"white","sd_width":"140","sd_invert":true,"styleid":"block-xu9bmn6lkf"} -->
	[bs_shape_divider sd=\'curve\'  sd_position=\'bottom\'  sd_color=\'white\'  sd_custom_color=\'#0073aa\'  sd_width=\'140\'  sd_height=\'100\'  sd_flip=\'false\'  sd_invert=\'true\'  sd_btf=\'false\'  styleid=\'block-xu9bmn6lkf\' ]<div class="wp-block-blockstrap-blockstrap-widget-shape-divider block-xu9bmn6lkf blockstrap-shape blockstrap-shape-bottom position-absolute"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 100" preserveAspectRatio="none">	<path class="bg-white blockstrap-shape-fill" d="M500,97C126.7,96.3,0.8,19.8,0,0v100l1000,0V1C1000,19.4,873.3,97.8,500,97z"/></svg></div><style>.block-xu9bmn6lkf { pointer-events: none;background-repeat: no-repeat;bottom:  -1px; left: -1px;right: -1px;line-height: 0;overflow: hidden;}.block-xu9bmn6lkf svg{ height: 100px;width: calc(140% + 1.3px);left: 50%;position: relative;display: block;-webkit-transform: translateX(-50%); -ms-transform: translateX(-50%); transform: translateX(-50%);}.block-xu9bmn6lkf svg path{ }</style>[/bs_shape_divider]
	<!-- /wp:blockstrap/blockstrap-widget-shape-divider -->

	<!-- wp:blockstrap/blockstrap-widget-container {"mt_lg":"0","pt_lg":"5","pb_lg":"2"} -->
	[bs_container container=\'container\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'0\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'5\'  pr_lg=\'\'  pb_lg=\'2\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mt-0 mb-lg-3 pt-5 pb-2 container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols_lg":"1"} -->
		[bs_container container=\'row\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'1\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 row-cols-1 row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","text_align_lg":"text-lg-center","mt_lg":"4","mb_lg":"","pt_lg":"5"} -->
			[bs_container container=\'col\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'text-lg-center\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'4\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'5\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mt-4 pt-5 text-center col"><!-- wp:blockstrap/blockstrap-widget-archive-title {"text_color":"white"} -->
				[bs_archive_title html_tag=\'h1\'  text_color=\'white\'  text_color_custom=\'\'  font_size=\'\'  font_size_custom=\'\'  font_weight=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_on_text=\'false\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  css_class=\'\' ]
				<!-- /wp:blockstrap/blockstrap-widget-archive-title -->

				<!-- wp:term-description {"textColor":"white"} /--></div>[/bs_container]
			<!-- /wp:blockstrap/blockstrap-widget-container -->

			<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_md":"12","col_lg":"8","text_align_lg":"text-lg-center","mr_lg":"auto","mb_lg":"","ml_lg":"auto","pb_lg":"5"} -->
			[bs_container container=\'col\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'12\'  col_md=\'12\'  col_lg=\'8\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'text-lg-center\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'auto\'  mb_lg=\'\'  ml_lg=\'auto\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'5\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mr-auto ml-auto pb-5 col-12 col-md-12 col-lg-8 text-center col"><!-- wp:geodirectory/geodir-widget-search {"mt":"5","mb":"0","content":""} -->
				<div class="wp-block-geodirectory-geodir-widget-search">[gd_search post_type=\'\'  post_type_hide=\'false\'  hide_search_input=\'false\'  hide_near_input=\'false\'  bg=\'\'  mt=\'5\'  mr=\'\'  mb=\'0\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  show=\'\' ]</div>
				<!-- /wp:geodirectory/geodir-widget-search --></div>[/bs_container]
			<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
		<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
	<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","pt_lg":"3","anchor":"main"} -->
[bs_container container=\'container-fluid\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'3\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'main\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 pt-3 container-fluid" id="main"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","row_cols_md":"2","row_cols_lg":"2"} -->
	[bs_container container=\'row\'  row_cols=\'1\'  row_cols_md=\'2\'  row_cols_lg=\'2\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 row-cols-1 row-cols-md-2 row-cols-lg-2 row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","css_class":"z-index\u002d\u002d2"} -->
		[bs_container container=\'col\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'z-index--2\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 col z-index--2"><!-- wp:geodirectory/geodir-widget-loop-actions {"hide_layouts":["4","5"],"content":""} -->
			<div class="wp-block-geodirectory-geodir-widget-loop-actions">[gd_loop_actions hide_layouts=\'4,5\'  bg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\' ]</div>
			<!-- /wp:geodirectory/geodir-widget-loop-actions -->

			<!-- wp:geodirectory/geodir-widget-loop {"content":""} -->
			<div class="wp-block-geodirectory-geodir-widget-loop">[gd_loop layout=\'2\'  row_gap=\'\'  column_gap=\'\'  card_border=\'\'  card_shadow=\'\'  bg=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\' ]</div>
			<!-- /wp:geodirectory/geodir-widget-loop -->

			<!-- wp:geodirectory/geodir-widget-loop-paging {"content":""} -->
			<div class="wp-block-geodirectory-geodir-widget-loop-paging">[gd_loop_paging show_advanced=\'\'  mid_size=\'\'  bg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\' ]</div>
			<!-- /wp:geodirectory/geodir-widget-loop-paging --></div>[/bs_container]
		<!-- /wp:blockstrap/blockstrap-widget-container -->

		<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mt_lg":"5","pr_lg":"0","pl_lg":"0","css_class":"z-index-1"} -->
		[bs_container container=\'col\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'5\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'0\'  pb_lg=\'\'  pl_lg=\'0\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'z-index-1\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mt-5 mb-lg-3 pr-0 pl-0 col z-index-1"><!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","mb_lg":"","pr_lg":"0","pl_lg":"0","position":"sticky-top","sticky_offset_top":115} -->
			[bs_container container=\'container-fluid\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'0\'  pb_lg=\'\'  pl_lg=\'0\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'sticky-top\'  sticky_offset_top=\'115\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 pr-0 pl-0 container-fluid sticky-top" style="top:115px"><!-- wp:geodirectory/geodir-widget-map {"height":"90vh"} -->
				[gd_map title=\'\'  width=\'100%\'  height=\'90vh\'  maptype=\'ROADMAP\'  zoom=\'0\'  map_type=\'auto\'  post_settings=\'true\'  post_type=\'\'  terms=\'\'  tick_terms=\'\'  tags=\'\'  all_posts=\'false\'  post_id=\'\'  search_filter=\'false\'  post_type_filter=\'false\'  cat_filter=\'false\'  child_collapse=\'false\'  map_directions=\'false\'  scrollwheel=\'false\'  hide_zoom_control=\'false\'  hide_street_control=\'false\'  sticky=\'false\'  static=\'false\'  bg=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\' ]<div class="bsui" style="overflow:hidden;height:90vh" class="wp-block-geodirectory-geodir-widget-map"><img title="Placeholder map" src="http://localhost/wp-content/plugins/geodirectory/assets/images/block-placeholder-map.png" alt="Placeholder" width="100%" height="90vh" style="height:inherit;object-fit:cover" class="mb- mt- ml- mr- pb- pt- pl- pr- border border-   rounded- bg-"/></div>[/gd_map]
				<!-- /wp:geodirectory/geodir-widget-map --></div>[/bs_container]
			<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
		<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
	<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:spacer {"height":"30px"} -->
<div style="height:30px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->';
	}

	/**
	 * Add content to the GD archive page template of the BLockStrap theme.
	 *
	 * @param $content
	 *
	 * @return string
	 */
	public static function archive_template( $content ) {
		return '<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-gradient","bg_gradient":"linear-gradient(135deg,rgb(2,11,185) 2%,rgb(126,5,170) 100%)","position":"position-relative"} -->
[bs_container container=\'container-fluid\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'custom-gradient\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgb(2,11,185) 2%,rgb(126,5,170) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'position-relative\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 bg-custom-gradient container-fluid position-relative" style="background-image:linear-gradient(135deg,rgb(2,11,185) 2%,rgb(126,5,170) 100%)"><!-- wp:blockstrap/blockstrap-widget-shape-divider {"sd":"curve","sd_position":"bottom","sd_color":"white","sd_width":"140","sd_invert":true,"styleid":"block-xu9bmn6lkf"} -->
	[bs_shape_divider sd=\'curve\'  sd_position=\'bottom\'  sd_color=\'white\'  sd_custom_color=\'#0073aa\'  sd_width=\'140\'  sd_height=\'100\'  sd_flip=\'false\'  sd_invert=\'true\'  sd_btf=\'false\'  styleid=\'block-xu9bmn6lkf\' ]<div class="wp-block-blockstrap-blockstrap-widget-shape-divider block-xu9bmn6lkf blockstrap-shape blockstrap-shape-bottom position-absolute"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 100" preserveAspectRatio="none">	<path class="bg-white blockstrap-shape-fill" d="M500,97C126.7,96.3,0.8,19.8,0,0v100l1000,0V1C1000,19.4,873.3,97.8,500,97z"/></svg></div><style>.block-xu9bmn6lkf { pointer-events: none;background-repeat: no-repeat;bottom:  -1px; left: -1px;right: -1px;line-height: 0;overflow: hidden;}.block-xu9bmn6lkf svg{ height: 100px;width: calc(140% + 1.3px);left: 50%;position: relative;display: block;-webkit-transform: translateX(-50%); -ms-transform: translateX(-50%); transform: translateX(-50%);}.block-xu9bmn6lkf svg path{ }</style>[/bs_shape_divider]
	<!-- /wp:blockstrap/blockstrap-widget-shape-divider -->

	<!-- wp:blockstrap/blockstrap-widget-container {"mt_lg":"0","pt_lg":"5","pb_lg":"2"} -->
	[bs_container container=\'container\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'0\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'5\'  pr_lg=\'\'  pb_lg=\'2\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mt-0 mb-lg-3 pt-5 pb-2 container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols_lg":"1"} -->
		[bs_container container=\'row\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'1\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 row-cols-1 row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","text_align_lg":"text-lg-center","mt_lg":"4","mb_lg":"","pt_lg":"5"} -->
			[bs_container container=\'col\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'text-lg-center\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'4\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'5\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mt-4 pt-5 text-center col"><!-- wp:blockstrap/blockstrap-widget-archive-title {"text_color":"white"} -->
				[bs_archive_title html_tag=\'h1\'  text_color=\'white\'  text_color_custom=\'\'  font_size=\'\'  font_size_custom=\'\'  font_weight=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_on_text=\'false\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  css_class=\'\' ]
				<!-- /wp:blockstrap/blockstrap-widget-archive-title -->

				<!-- wp:term-description {"textColor":"white"} /--></div>[/bs_container]
			<!-- /wp:blockstrap/blockstrap-widget-container -->

			<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_md":"12","col_lg":"8","text_align_lg":"text-lg-center","mr_lg":"auto","mb_lg":"","ml_lg":"auto","pb_lg":"5"} -->
			[bs_container container=\'col\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'12\'  col_md=\'12\'  col_lg=\'8\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'text-lg-center\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'auto\'  mb_lg=\'\'  ml_lg=\'auto\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'5\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mr-auto ml-auto pb-5 col-12 col-md-12 col-lg-8 text-center col"><!-- wp:geodirectory/geodir-widget-search {"mt":"5","mb":"0","content":""} -->
				<div class="wp-block-geodirectory-geodir-widget-search">[gd_search post_type=\'\'  post_type_hide=\'false\'  hide_search_input=\'false\'  hide_near_input=\'false\'  bg=\'\'  mt=\'5\'  mr=\'\'  mb=\'0\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  show=\'\' ]</div>
				<!-- /wp:geodirectory/geodir-widget-search --></div>[/bs_container]
			<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
		<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
	<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","pt_lg":"3","anchor":"main"} -->
[bs_container container=\'container-fluid\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'3\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'main\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 pt-3 container-fluid" id="main"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","row_cols_md":"2","row_cols_lg":"2"} -->
	[bs_container container=\'row\'  row_cols=\'1\'  row_cols_md=\'2\'  row_cols_lg=\'2\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 row-cols-1 row-cols-md-2 row-cols-lg-2 row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","css_class":"z-index\u002d\u002d2"} -->
		[bs_container container=\'col\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'\'  pb_lg=\'\'  pl_lg=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'z-index--2\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mb-lg-3 col z-index--2"><!-- wp:geodirectory/geodir-widget-loop-actions {"hide_layouts":["4","5"],"content":""} -->
			<div class="wp-block-geodirectory-geodir-widget-loop-actions">[gd_loop_actions hide_layouts=\'4,5\'  bg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\' ]</div>
			<!-- /wp:geodirectory/geodir-widget-loop-actions -->

			<!-- wp:geodirectory/geodir-widget-loop {"content":""} -->
			<div class="wp-block-geodirectory-geodir-widget-loop">[gd_loop layout=\'2\'  row_gap=\'\'  column_gap=\'\'  card_border=\'\'  card_shadow=\'\'  bg=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\' ]</div>
			<!-- /wp:geodirectory/geodir-widget-loop -->

			<!-- wp:geodirectory/geodir-widget-loop-paging {"content":""} -->
			<div class="wp-block-geodirectory-geodir-widget-loop-paging">[gd_loop_paging show_advanced=\'\'  mid_size=\'\'  bg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\' ]</div>
			<!-- /wp:geodirectory/geodir-widget-loop-paging --></div>[/bs_container]
		<!-- /wp:blockstrap/blockstrap-widget-container -->

		<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mt_lg":"5","pr_lg":"0","pl_lg":"0","css_class":"z-index-1"} -->
		[bs_container container=\'col\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'5\'  mr_lg=\'\'  mb_lg=\'3\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'0\'  pb_lg=\'\'  pl_lg=\'0\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'\'  sticky_offset_top=\'\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'z-index-1\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 mt-5 mb-lg-3 pr-0 pl-0 col z-index-1"><!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","mb_lg":"","pr_lg":"0","pl_lg":"0","position":"sticky-top","sticky_offset_top":115} -->
			[bs_container container=\'container-fluid\'  row_cols=\'\'  row_cols_md=\'\'  row_cols_lg=\'\'  col=\'\'  col_md=\'\'  col_lg=\'\'  bg=\'\'  bg_color=\'#0073aa\'  bg_gradient=\'linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)\'  bg_image_fixed=\'false\'  bg_image_use_featured=\'false\'  bg_image=\'\'  bg_image_id=\'\'  bg_image_xy=\'{x:undefined,y:undefined}\'  bg_on_text=\'false\'  text_color=\'\'  text_justify=\'false\'  text_align=\'\'  text_align_md=\'\'  text_align_lg=\'\'  mt=\'\'  mr=\'\'  mb=\'3\'  ml=\'\'  mt_md=\'\'  mr_md=\'\'  mb_md=\'\'  ml_md=\'\'  mt_lg=\'\'  mr_lg=\'\'  mb_lg=\'\'  ml_lg=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  pt_md=\'\'  pr_md=\'\'  pb_md=\'\'  pl_md=\'\'  pt_lg=\'\'  pr_lg=\'0\'  pb_lg=\'\'  pl_lg=\'0\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\'  position=\'sticky-top\'  sticky_offset_top=\'115\'  sticky_offset_bottom=\'\'  display=\'\'  display_md=\'\'  display_lg=\'\'  flex_align_items=\'\'  flex_align_items_md=\'\'  flex_align_items_lg=\'\'  flex_justify_content=\'\'  flex_justify_content_md=\'\'  flex_justify_content_lg=\'\'  flex_align_self=\'\'  flex_align_self_md=\'\'  flex_align_self_lg=\'\'  flex_order=\'\'  flex_order_md=\'\'  flex_order_lg=\'\'  anchor=\'\'  css_class=\'\' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-3 pr-0 pl-0 container-fluid sticky-top" style="top:115px"><!-- wp:geodirectory/geodir-widget-map {"height":"90vh"} -->
				[gd_map title=\'\'  width=\'100%\'  height=\'90vh\'  maptype=\'ROADMAP\'  zoom=\'0\'  map_type=\'auto\'  post_settings=\'true\'  post_type=\'\'  terms=\'\'  tick_terms=\'\'  tags=\'\'  all_posts=\'false\'  post_id=\'\'  search_filter=\'false\'  post_type_filter=\'false\'  cat_filter=\'false\'  child_collapse=\'false\'  map_directions=\'false\'  scrollwheel=\'false\'  hide_zoom_control=\'false\'  hide_street_control=\'false\'  sticky=\'false\'  static=\'false\'  bg=\'\'  mt=\'\'  mr=\'\'  mb=\'\'  ml=\'\'  pt=\'\'  pr=\'\'  pb=\'\'  pl=\'\'  border=\'\'  rounded=\'\'  rounded_size=\'\'  shadow=\'\' ]<div class="bsui" style="overflow:hidden;height:90vh" class="wp-block-geodirectory-geodir-widget-map"><img title="Placeholder map" src="http://localhost/wp-content/plugins/geodirectory/assets/images/block-placeholder-map.png" alt="Placeholder" width="100%" height="90vh" style="height:inherit;object-fit:cover" class="mb- mt- ml- mr- pb- pt- pl- pr- border border-   rounded- bg-"/></div>[/gd_map]
				<!-- /wp:geodirectory/geodir-widget-map --></div>[/bs_container]
			<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
		<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
	<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:spacer {"height":"30px"} -->
<div style="height:30px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->';
	}




}

GeoDir_BlockStrap::init();
