<?php
/**
 * GeoDirectory v1 to v2 conversion class.
 *
 * @author   AyeCode
 * @category Admin
 * @package  GeoDirectory/Classes
 * @version  2.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * GeoDir_Admin_Upgrade Class.
 */
class GeoDir_Admin_Upgrade {

	public static function init() {
		// Start
		self::start_conversion();

		// Options
		self::convert_options();

		// Fields
		self::convert_fields();

		// Categories & Tags
		self::convert_terms();

		// Posts
		self::convert_posts();

		// End
		self::end_conversion();
	}

	public static function start_conversion() {
		do_action( 'geodir_v1_to_v2_start_conversion' );
	}

	public static function convert_options() {
		do_action( 'geodir_v1_to_v2_convert_options_before' );

		$options = self::get_options();

		do_action( 'geodir_v1_to_v2_convert_options_after' );
	}

	public static function convert_fields() {
		do_action( 'geodir_v1_to_v2_convert_fields_before' );

		do_action( 'geodir_v1_to_v2_convert_fields_after' );
	}

	public static function convert_terms() {
		do_action( 'geodir_v1_to_v2_convert_terms_before' );

		do_action( 'geodir_v1_to_v2_convert_terms_after' );
	}

	public static function convert_posts() {
		do_action( 'geodir_v1_to_v2_convert_posts_before' );

		do_action( 'geodir_v1_to_v2_convert_posts_after' );
	}

	public static function end_conversion() {
		do_action( 'geodir_v1_to_v2_end_conversion' );
	}

	public static function get_options() {
		$old_options = array( 'geodir_un_geodirectory', 'geodir_default_data_installed', 'geodir_default_data_installed_1.2.8', 'geodir_theme_location_nav', 'geodir_exclude_post_type_on_map', 'geodir_exclude_cat_on_map', 'geodir_exclude_cat_on_map_upgrade', 'geodir_default_map_language', 'geodir_default_map_search_pt', 'avada_nag', 'gd_convert_custom_field_display', 'gd_facebook_button', 'gd_ga_access_token', 'gd_ga_refresh_token', 'gd_google_button', 'gd_search_dist', 'gd_term_icons', 'gd_theme_compats', 'gd_tweet_button', 'geodir_changes_in_custom_fields_table', 'geodir_default_location', 'geodir_disable_yoast_meta', 'geodir_ga_client_id', 'geodir_ga_client_secret', 'geodir_ga_tracking_code', 'geodir_gd_uids', 'geodir_global_review_count', 'geodir_listing_page', 'post_types', 'geodir_remove_unnecessary_fields', 'geodir_remove_url_seperator', 'geodir_set_post_attachments', 'geodir_sidebars', 'taxonomies', 'geodir_use_php_sessions', 'geodir_wpml_disable_duplicate', 'geodirectory_list_thumbnail_size', 'ptthemes_auto_login', 'ptthemes_listing_preexpiry_notice_days', 'ptthemes_logoin_page_content', 'ptthemes_reg_page_content', 'theme_compatibility_setting' );

		$results = $wpdb->get_results( "SELECT option_name FROM " . $wpdb->options . " WHERE option_name LIKE 'geodir_un_%' OR option_name LIKE 'geodir_theme_location_nav_%'" );
		if ( !empty( $results ) ) {
			foreach ( $results as $row ) {
				$old_options[] = $row->option_name;
			}
		}
/*
|gd_cafecategory_children
|gd_convert_custom_field_display
|gd_eventcategory_children
|gd_ga_access_token
|gd_ga_refresh_token
|gd_gamecategory_children
|gd_hotelcategory_children
|gd_location_sitemap_exclude_cats
|gd_location_sitemap_exclude_location
|gd_location_sitemap_exclude_tags
|gd_placecategory_children
|gd_sportcategory_children
|gd_tag_salecategory_children
|gd_term_icons
|gd_testcategory_children
|gd_theme_compat
|gd_theme_compats
|gd_update_uname
|gd_update_upass
|gd_websitecategory_children
|gdbh_price_table_updated
|gdevents_db_version
|gdevents_installed
|gdf
|gdf_db_version
|gdf-transients
|gdfi_config
|gdfi_config_yelp
|gdpr_add_consent_checkboxes_checkout
|gdpr_add_consent_checkboxes_registration
|gdpr_disable_css
|gdpr_enable_telemetry_tracker
|gdpr_recaptcha_secret_key
|gdpr_recaptcha_site_key
|gdpr_use_recaptcha
|gdw_db_version
|genesis_responsive_slider_settings
|geodir_accept_term_condition
|geodir_add_categories_url
|geodir_add_list_page
|geodir_add_listing_link_add_listing_nav
|geodir_add_listing_link_user_dashboard
|geodir_add_listing_mouse_scroll
|geodir_add_listing_page
|geodir_add_location_url
|geodir_add_posttype_in_listing_nav
|geodir_add_related_listing_posttypes
|geodir_allow_coupon_code
|geodir_allow_cpass
|geodir_allow_posttype_frontend
|geodir_allow_wpadmin
|geodir_author_desc_word_limit
|geodir_author_view
|geodir_autocompleter_autosubmit
|geodir_autocompleter_autosubmit_near
|geodir_autocompleter_filter_location
|geodir_autocompleter_matches_label
|geodir_autocompleter_max_results
|geodir_autocompleter_min_chars
|geodir_autolocate_ask
|geodir_autolocate_disable
|geodir_bcc_enquiry
|geodir_bcc_expire
|geodir_bcc_friend
|geodir_bcc_invoice
|geodir_bcc_listing_published
|geodir_bcc_new_user
|geodir_business_hours_activation_redirect
|geodir_business_hours_day_name
|geodir_business_hours_disable_widget
|geodir_business_hours_highlight_open_hours
|geodir_business_hours_instruction_text
|geodir_business_hours_precheck_no_hours
|geodir_business_hours_replace_timing
|geodir_business_hours_section_header
|geodir_business_hours_show_closed_today
|geodir_business_hours_show_open_footer
|geodir_business_hours_show_open_header
|geodir_business_hours_show_open_status
|geodir_business_hours_show_status_widget
|geodir_business_hours_time_format
|geodir_cat_loc_gd_cafe_195
|geodir_cat_loc_gd_cafe_196
|geodir_cat_loc_gd_cafe_197
|geodir_cat_loc_gd_event_32
|geodir_cat_loc_gd_event_32_1
|geodir_cat_loc_gd_event_32_11
|geodir_cat_loc_gd_event_32_14
|geodir_cat_loc_gd_event_32_15
|geodir_cat_loc_gd_event_32_16
|geodir_cat_loc_gd_event_32_17
|geodir_cat_loc_gd_event_32_18
|geodir_cat_loc_gd_event_32_19
|geodir_cat_loc_gd_event_32_2
|geodir_cat_loc_gd_event_32_20
|geodir_cat_loc_gd_event_32_21
|geodir_cat_loc_gd_event_32_22
|geodir_cat_loc_gd_event_32_23
|geodir_cat_loc_gd_event_32_24
|geodir_cat_loc_gd_event_32_25
|geodir_cat_loc_gd_event_32_26
|geodir_cat_loc_gd_event_32_27
|geodir_cat_loc_gd_event_32_28
|geodir_cat_loc_gd_event_32_29
|geodir_cat_loc_gd_event_32_3
|geodir_cat_loc_gd_event_32_4
|geodir_cat_loc_gd_event_32_5
|geodir_cat_loc_gd_event_32_6
|geodir_cat_loc_gd_event_32_7
|geodir_cat_loc_gd_event_32_8
|geodir_cat_loc_gd_event_331
|geodir_cat_loc_gd_place_111
|geodir_cat_loc_gd_place_3
|geodir_cat_loc_gd_place_3_1
|geodir_cat_loc_gd_place_3_11
|geodir_cat_loc_gd_place_3_110
|geodir_cat_loc_gd_place_3_14
|geodir_cat_loc_gd_place_3_15
|geodir_cat_loc_gd_place_3_16
|geodir_cat_loc_gd_place_3_17
|geodir_cat_loc_gd_place_3_18
|geodir_cat_loc_gd_place_3_19
|geodir_cat_loc_gd_place_3_2
|geodir_cat_loc_gd_place_3_20
|geodir_cat_loc_gd_place_3_21
|geodir_cat_loc_gd_place_3_22
|geodir_cat_loc_gd_place_3_23
|geodir_cat_loc_gd_place_3_24
|geodir_cat_loc_gd_place_3_25
|geodir_cat_loc_gd_place_3_26
|geodir_cat_loc_gd_place_3_27
|geodir_cat_loc_gd_place_3_28
|geodir_cat_loc_gd_place_3_29
|geodir_cat_loc_gd_place_3_3
|geodir_cat_loc_gd_place_3_34
|geodir_cat_loc_gd_place_3_38
|geodir_cat_loc_gd_place_3_4
|geodir_cat_loc_gd_place_3_456
|geodir_cat_loc_gd_place_3_5
|geodir_cat_loc_gd_place_3_6
|geodir_cat_loc_gd_place_3_7
|geodir_cat_loc_gd_place_3_8
|geodir_cat_loc_gd_place_3_co_australia
|geodir_cat_loc_gd_place_3_co_belgium
|geodir_cat_loc_gd_place_3_co_burma
|geodir_cat_loc_gd_place_3_co_canada
|geodir_cat_loc_gd_place_3_co_costa-rica-cote
|geodir_cat_loc_gd_place_3_co_cote-divoiree
|geodir_cat_loc_gd_place_3_co_germany
|geodir_cat_loc_gd_place_3_co_india
|geodir_cat_loc_gd_place_3_co_russia
|geodir_cat_loc_gd_place_3_co_united-kingdom
|geodir_cat_loc_gd_place_3_co_united-states
|geodir_cat_loc_gd_place_3_re_australia_queensland
|geodir_cat_loc_gd_place_3_re_belgium_region-wallonne
|geodir_cat_loc_gd_place_3_re_canada_ontario
|geodir_cat_loc_gd_place_3_re_costa-rica-cote_provincia-de-san-jose
|geodir_cat_loc_gd_place_3_re_germany_bayern
|geodir_cat_loc_gd_place_3_re_india_gujarat
|geodir_cat_loc_gd_place_4
|geodir_cat_loc_gd_place_433
|geodir_cat_loc_gd_place_482
|geodir_cat_loc_gd_place_5
|geodir_cat_loc_gd_place_503
|geodir_cat_loc_gd_place_503_1
|geodir_cat_loc_gd_place_503_110
|geodir_cat_loc_gd_place_503_111
|geodir_cat_loc_gd_place_507
|geodir_cat_loc_gd_place_589
|geodir_cat_loc_gd_place_689
|geodir_cat_loc_gd_place_689_co_australia
|geodir_cat_loc_gd_place_690
|geodir_cat_loc_gd_place_780
|geodir_cat_loc_gd_place_9
|geodir_cat_loc_gd_place_9_1
|geodir_cat_loc_gd_place_9_110
|geodir_cat_loc_gd_place_9_co_australia
|geodir_cat_loc_gd_place_9_co_germany
|geodir_cat_loc_gd_place_9_co_india
|geodir_cat_loc_gd_place_9_re_australia_queensland
|geodir_cat_loc_gd_place_9_re_india_gujarat
|geodir_cat_loc_gd_sport_247
|geodir_cat_loc_gd_sport_251
|geodir_cat_loc_gd_sport_90
|geodir_cat_loc_gd_sport_90_31
|geodir_cat_loc_gd_test_563_re_united-states_district-of-columbia
|geodir_cat_loc_gd_test_563_re_united-states_florida
|geodir_cat_loc_gd_test_660
|geodir_cat_loc_gd_test_660_co_australia
|geodir_cat_loc_gd_test_660_co_belgien
|geodir_cat_loc_gd_test_662
|geodir_cat_loc_gd_test_665_22
|geodir_cat_loc_gd_test_665_27
|geodir_cat_loc_gd_website_133
|geodir_cat_loc_gd_website_134
|geodir_cat_loc_gd_website_135
|geodir_cat_loc_gd_website_136
|geodir_cat_loc_gd_website_137
|geodir_cat_loc_gd_website_138
|geodir_cat_loc_gd_website_139
|geodir_cat_loc_gd_website_140
|geodir_cat_loc_gd_website_141
|geodir_cat_loc_gd_website_142
|geodir_cat_loc_gd_website_143
|geodir_cat_loc_gd_website_145
|geodir_cat_loc_gd_website_146
|geodir_cat_loc_gd_website_147
|geodir_cat_loc_gd_website_148
|geodir_cat_loc_gd_website_150
|geodir_cat_loc_gd_website_155
|geodir_cat_loc_gd_website_162
|geodir_cat_loc_gd_website_164
|geodir_cat_loc_gd_website_167
|geodir_cat_loc_gd_website_175
|geodir_cat_loc_gd_website_184
|geodir_cat_loc_gd_website_185
|geodir_changes_in_custom_fields_table
|geodir_changes_in_invoice_table_1_2_3
|geodir_changes_in_invoice_table_1_2_3_1
|geodir_changes_in_invoice_table_1_2_5
|geodir_changes_in_invoice_table_1_2_6
|geodir_changes_in_package_table
|geodir_changes_in_package_table_hide_related
|geodir_changes_in_package_table_limit
|geodir_changes_in_package_table_trial_units
|geodir_checkout_page
|geodir_claim_approved_email_content
|geodir_claim_approved_email_subject
|geodir_claim_auto_approve
|geodir_claim_auto_approve_email_content
|geodir_claim_auto_approve_email_subject
|geodir_claim_email_content
|geodir_claim_email_content_admin
|geodir_claim_email_subject
|geodir_claim_email_subject_admin
|geodir_claim_enable
|geodir_claim_fields_upgrade
|geodir_claim_force_upgrade
|geodir_claim_rejected_email_content
|geodir_claim_rejected_email_subject
|geodir_claim_show_author_link
|geodir_claim_show_owner_varified
|geodir_coustem_css
|geodir_cpt_disable_location
|geodir_cpt_img_gd_cafe
|geodir_cpt_img_gd_event
|geodir_cpt_img_gd_place
|geodir_cpt_img_gd_test
|geodir_currency
|geodir_currencysym
|geodir_custom_gmaps_detail
|geodir_custom_gmaps_home
|geodir_custom_gmaps_listing
|geodir_custom_gmaps_style_detail
|geodir_custom_gmaps_style_home
|geodir_custom_gmaps_style_listing
|geodir_custom_google_maps_activation_redirect_opt
|geodir_custom_post_types
|geodir_custom_posts_db_version
|geodir_default_data_installed
|geodir_default_location
|geodir_default_map_language
|geodir_default_map_search_pt
|geodir_default_marker_icon
|geodir_default_rating_star_icon
|geodir_desc_word_limit
|geodir_detail_sidebar_left_section
|geodir_disable_gb_modal
|geodir_disable_google_analytics_section
|geodir_disable_listing_info_section
|geodir_disable_perm_delete
|geodir_disable_rating
|geodir_disable_rating_cpt
|geodir_disable_rating_info_section
|geodir_disable_sharethis_button_section
|geodir_disable_tabs
|geodir_disable_tfg_buttons_section
|geodir_disable_user_links_section
|geodir_disable_yoast_meta
|geodir_duplicate_field_gd_cafe
|geodir_duplicate_field_gd_event
|geodir_duplicate_field_gd_hotel
|geodir_duplicate_field_gd_place
|geodir_duplicate_field_gd_sport
|geodir_duplicate_field_gd_test
|geodir_duplicate_field_gd_website
|geodir_email_enquiry_content
|geodir_email_enquiry_subject
|geodir_email_friend_content
|geodir_email_friend_subject
|geodir_enable_autocompleter
|geodir_enable_autocompleter_near
|geodir_enable_city
|geodir_enable_country
|geodir_enable_map_cache
|geodir_enable_region
|geodir_event_date_format
|geodir_event_date_format_custom
|geodir_event_date_format_feild
|geodir_event_date_use_custom
|geodir_event_defalt_filter
|geodir_event_delete_unnecessary_fields
|geodir_event_disable_recurring
|geodir_event_enable_recurring
|geodir_event_hide_past_dates
|geodir_event_infowindow_dates_count
|geodir_event_infowindow_dates_filter
|geodir_event_link_any
|geodir_event_linked_count
|geodir_event_linked_event_type
|geodir_event_linked_listing_view
|geodir_event_linked_post_excerpt
|geodir_event_linked_sortby
|geodir_event_recurring_feature
|geodir_event_recurring_option
|geodir_everywhere_in_city_dropdown
|geodir_everywhere_in_country_dropdown
|geodir_everywhere_in_region_dropdown
|geodir_exclude_cat_on_map
|geodir_exclude_cat_on_map_upgrade
|geodir_exclude_post_type_on_map
|geodir_favorite_link_user_dashboard
|geodir_first_load_redirect
|geodir_footer_scripts
|geodir_forgot_password_content
|geodir_forgot_password_subject
|geodir_franchise_bcc_admin_payment_franchises
|geodir_franchise_client_email_message_payment_franchises
|geodir_franchise_client_email_subject_payment_franchises
|geodir_franchise_disable_viewing
|geodir_franchise_hide_main
|geodir_franchise_hide_main_all
|geodir_franchise_hide_main_m
|geodir_franchise_hide_main_s
|geodir_franchise_hide_viewing
|geodir_franchise_post_count
|geodir_franchise_post_enable_link
|geodir_franchise_post_enable_tab
|geodir_franchise_post_excerpt
|geodir_franchise_post_listing_view
|geodir_franchise_post_location_filter
|geodir_franchise_post_sortby
|geodir_franchise_posttypes
|geodir_franchise_posttypess
|geodir_franchise_show_franchises_link
|geodir_franchise_show_main
|geodir_franchise_show_parent_link
|geodir_ga_add_tracking_code
|geodir_ga_anonymize_ip
|geodir_ga_auth_code
|geodir_ga_auto_refresh
|geodir_ga_client_id
|geodir_ga_client_secret
|geodir_ga_id
|geodir_ga_no_refresh
|geodir_ga_pass
|geodir_ga_refresh_time
|geodir_ga_stats
|geodir_ga_tracking_code
|geodir_ga_user
|geodir_gd_booster_notices
|geodir_gd_booster_options
|geodir_gdpr_erase_reviews
|geodir_gdpr_export_cpt
|geodir_gdpr_export_reviews
|geodir_global_review_count
|geodir_google_api_key
|geodir_google_wallet_3
|geodir_header_scripts
|geodir_home_go_to
|geodir_home_map_untick
|geodir_home_page
|geodir_info_page
|geodir_installed
|geodir_invoice_page
|geodir_invoices_page
|geodir_lazy_load
|geodir_licence_keys
|geodir_linked_post_types
|geodir_listing_ex_status
|geodir_listing_expiry
|geodir_listing_hover_bounce_map_pin
|geodir_listing_img_size
|geodir_listing_link_user_dashboard
|geodir_listing_new_days
|geodir_listing_no_img
|geodir_listing_preexpiry_notice_days
|geodir_listing_preexpiry_notice_days_3
|geodir_listing_preexpiry_notice_days2
|geodir_listing_preexpiry_notice_days3
|geodir_listing_preexpiry_notice_disable
|geodir_listing_prefix
|geodir_listing_view
|geodir_load_map
|geodir_location_disable_term_auto_count
|geodir_location_hide_country_part
|geodir_location_hide_region_part
|geodir_location_no_of_records
|geodir_location_page
|geodir_location_switcher_list_mode
|geodir_login_page
|geodir_map_onoff_dragging
|geodir_marker_cluster_on_maps
|geodir_marker_cluster_size
|geodir_marker_cluster_type
|geodir_marker_cluster_zoom
|geodir_messages
|geodir_meta_desc_add-listing
|geodir_meta_desc_author
|geodir_meta_desc_detail
|geodir_meta_desc_homepage
|geodir_meta_desc_listing
|geodir_meta_desc_listing-success
|geodir_meta_desc_location
|geodir_meta_desc_login
|geodir_meta_desc_pt
|geodir_meta_desc_search
|geodir_meta_title_add-listing
|geodir_meta_title_author
|geodir_meta_title_detail
|geodir_meta_title_homepage
|geodir_meta_title_listing
|geodir_meta_title_listing-success
|geodir_meta_title_location
|geodir_meta_title_login
|geodir_meta_title_pt
|geodir_meta_title_search
|geodir_near_field_default_text
|geodir_near_me_dist
|geodir_new_post_default_status
|geodir_notify_post_edited
|geodir_notify_post_submit
|geodir_page_title_add-listing
|geodir_page_title_author
|geodir_page_title_cat-listing
|geodir_page_title_edit-listing
|geodir_page_title_favorite
|geodir_page_title_pt
|geodir_page_title_tag-listing
|geodir_pagination_advance_info
|geodir_paid_listing_status
|geodir_payment_currency_position
|geodir_payment_expire_date_on_detail
|geodir_payment_expire_date_on_listing
|geodir_payment_free_package_renew
|geodir_payment_invoice_email_body
|geodir_payment_invoice_email_subject
|geodir_payment_invoice_prefix
|geodir_payment_invoice_threshold
|geodir_payment_package_table_has_upgrades
|geodir_payment_pages_installed
|geodir_payment_remove_unnecessary_fields
|geodir_payments_db_version
|geodir_post_added_success_msg_content
|geodir_post_edited_email_content_admin
|geodir_post_edited_email_subject_admin
|geodir_post_payment_fail_admin_email_content
|geodir_post_payment_fail_admin_email_subject
|geodir_post_payment_success_admin_email_content
|geodir_post_payment_success_admin_email_subject
|geodir_post_payment_success_client_email_content
|geodir_post_payment_success_client_email_subject
|geodir_post_published_email_content
|geodir_post_published_email_subject
|geodir_post_renew_success_email_content
|geodir_post_renew_success_email_content_admin
|geodir_post_renew_success_email_subject
|geodir_post_renew_success_email_subject_admin
|geodir_post_submited_success_email_content
|geodir_post_submited_success_email_content_admin
|geodir_post_submited_success_email_subject
|geodir_post_submited_success_email_subject_admin
|geodir_post_types
|geodir_post_types_claim_listing
|geodir_post_types_duplicate
|geodir_post_upgrade_success_email_content
|geodir_post_upgrade_success_email_content_admin
|geodir_post_upgrade_success_email_subject
|geodir_post_upgrade_success_email_subject_admin
|geodir_preview_page
|geodir_recaptcha_add_listing
|geodir_recaptcha_claim_listing
|geodir_recaptcha_client_version
|geodir_recaptcha_comments
|geodir_recaptcha_registration
|geodir_recaptcha_role_administrator
|geodir_recaptcha_role_author
|geodir_recaptcha_role_bbp_blocked
|geodir_recaptcha_role_bbp_keymaster
|geodir_recaptcha_role_bbp_spectator
|geodir_recaptcha_role_contributor
|geodir_recaptcha_role_editor
|geodir_recaptcha_role_shop_accountant
|geodir_recaptcha_role_shop_manager
|geodir_recaptcha_role_shop_vendor
|geodir_recaptcha_role_shop_worker
|geodir_recaptcha_role_subscriber
|geodir_recaptcha_secret_key
|geodir_recaptcha_send_enquery
|geodir_recaptcha_send_to_friend
|geodir_recaptcha_site_key
|geodir_recaptcha_theme
|geodir_recaptcha_title
|geodir_recaptcha_wp_registration
|geodir_registration_success_email_content
|geodir_registration_success_email_subject
|geodir_related_post_count
|geodir_related_post_excerpt
|geodir_related_post_listing_view
|geodir_related_post_location_filter
|geodir_related_post_relate_to
|geodir_related_post_sortby
|geodir_remove_unnecessary_fields
|geodir_remove_url_seperator
|geodir_renew_email_content
|geodir_renew_email_content2
|geodir_renew_email_content3
|geodir_renew_email_subject
|geodir_renew_email_subject2
|geodir_renew_email_subject3
|geodir_result_by_location
|geodir_review_count_force_update
|geodir_reviewrating_change_star_lables_field
|geodir_reviewrating_db_version
|geodir_reviewrating_enable_font_awesome
|geodir_reviewrating_enable_images
|geodir_reviewrating_enable_rating
|geodir_reviewrating_enable_rating_summary
|geodir_reviewrating_enable_review
|geodir_reviewrating_enable_sorting
|geodir_reviewrating_fa_full_rating_color
|geodir_reviewrating_hide_rating_summary
|geodir_reviewrating_liked_by
|geodir_reviewrating_optional_multirating
|geodir_reviewrating_overall_color
|geodir_reviewrating_overall_color_featured
|geodir_reviewrating_overall_count
|geodir_reviewrating_overall_off_img
|geodir_reviewrating_overall_off_img_featured
|geodir_reviewrating_overall_off_img_height
|geodir_reviewrating_overall_off_img_height_featured
|geodir_reviewrating_overall_off_img_width
|geodir_reviewrating_overall_off_img_width_featured
|geodir_reviewrating_overall_rating_texts
|geodir_reviewrating_review_like_img
|geodir_reviewrating_review_unlike_img
|geodir_reviewratings_db_version
|geodir_scss_core
|geodir_search_button_label
|geodir_search_display_searched_params
|geodir_search_dist
|geodir_search_dist_1
|geodir_search_dist_2
|geodir_search_field_default_text
|geodir_search_near_addition
|geodir_search_view
|geodir_search_word_limit
|geodir_set_as_home
|geodir_settings
|geodir_show_addlisting_nav
|geodir_show_author_bottom_section
|geodir_show_author_left_section
|geodir_show_author_right_section
|geodir_show_author_top_section
|geodir_show_changelocation_nave
|geodir_show_detail_bottom_section
|geodir_show_detail_top_section
|geodir_show_home_bottom_section
|geodir_show_home_contant_section
|geodir_show_home_left_section
|geodir_show_home_right_section
|geodir_show_home_top_section
|geodir_show_listing_bottom_section
|geodir_show_listing_left_section
|geodir_show_listing_nav
|geodir_show_listing_right_section
|geodir_show_listing_top_section
|geodir_show_location_url
|geodir_show_search_bottom_section
|geodir_show_search_left_section
|geodir_show_search_old_search_from
|geodir_show_search_right_section
|geodir_show_search_top_section
|geodir_sidebars
|geodir_social_cpt_to_fb
|geodir_social_disable_auto_post
|geodir_social_disable_post_to_fb
|geodir_success_page
|geodir_tabs
|geodir_taxonomies
|geodir_term_condition_content
|geodir_term_condition_page
|geodir_theme_location_nav
|geodir_theme_location_nav_Avada
|geodir_theme_location_nav_Directory Starter
|geodir_theme_location_nav_Geo 1280 Theme
|geodir_theme_location_nav_GeoDirectory Framework
|geodir_theme_location_nav_Jupiter Child Theme
|geodir_theme_location_nav_Kleo
|geodir_theme_location_nav_Poseidon
|geodir_theme_location_nav_Supreme Directory
|geodir_theme_location_nav_Twenty Twelve
|geodir_theme_location_nav_Whoop
|geodir_theme_location_nav_Whoop Child
|geodir_tiny_editor
|geodir_tiny_editor_event_reg_on_add_listing
|geodir_tiny_editor_on_add_listing
|geodir_un_geodir_advance_search_filters
|geodir_un_geodir_ajax_duplicate_alert
|geodir_un_geodir_claim_listing
|geodir_un_geodir_custom_google_maps
|geodir_un_geodir_custom_posts
|geodir_un_geodir_event_manager
|geodir_un_geodir_franchise
|geodir_un_geodir_gd_booster
|geodir_un_geodir_location_manager
|geodir_un_geodir_marker_cluster
|geodir_un_geodir_payfast_payment_manager
|geodir_un_geodir_payment_manager
|geodir_un_geodir_recaptcha
|geodir_un_geodir_review_rating_manager
|geodir_un_geodir_sagepay_payment_manager
|geodir_un_geodir_social_importer
|geodir_un_geodir_stripe_payment_manager
|geodir_un_geodirectory
|geodir_update_locations_default_options
|geodir_upgrade_1.1.9
|geodir_upload_max_filesize
|geodir_use_php_sessions
|geodir_use_wp_media_large_size
|geodir_width_author_contant_section
|geodir_width_author_left_section
|geodir_width_author_right_section
|geodir_width_home_contant_section
|geodir_width_home_left_section
|geodir_width_home_right_section
|geodir_width_listing_contant_section
|geodir_width_listing_left_section
|geodir_width_listing_right_section
|geodir_width_search_contant_section
|geodir_width_search_left_section
|geodir_width_search_right_section
*/
		// Core options
		$options = array(
			'taxonomies' => get_option( 'geodir_taxonomies' ),
			'post_types' => get_option( 'geodir_post_types' ),
			'page_add' => get_option( 'geodir_add_listing_page' ),
			'page_location' => get_option( 'geodir_location_page' ),
			'email_name' => get_option( 'site_email_name' ),
		);

		// Google Analytics options
		$options = array(
			'ga_id' => get_option( 'geodir_ga_id' ),
			'ga_stats' => get_option( 'geodir_ga_stats' ),
			'ga_user' => get_option( 'geodir_ga_user' ),
			'ga_pass' => get_option( 'geodir_ga_pass' ),
			'ga_tracking_code' => get_option( 'geodir_ga_tracking_code' ),
			'ga_account_id' => get_option( 'geodir_ga_client_id' ),
			'ga_client_secret' => get_option( 'geodir_ga_client_secret' ),
			'ga_no_refresh' => get_option( 'geodir_ga_no_refresh' ),
			'ga_refresh_time' => get_option( 'geodir_ga_refresh_time' ),
			'ga_auto_refresh' => get_option( 'geodir_ga_auto_refresh' ),
			'ga_auth_code' => get_option( 'geodir_ga_auth_code' ),
			'ga_add_tracking_code' => get_option( 'geodir_ga_add_tracking_code' ),
			'ga_anonymize_ip' => get_option( 'geodir_ga_anonymize_ip' )			
		);

		return apply_filters( 'geodir_v1_to_v2_get_options', $options );
	}
}
