<?php
namespace AyeCode\GeoDirectory\Common;

/**
 * Assets Manager for GeoDirectory v3.
 *
 * Handles registration and enqueuing of scripts and styles generated by Vite.
 */
class Assets {

	/**
	 * The plugin version.
	 *
	 * @var string
	 */
	private $version;

	/**
	 * The root URL for assets.
	 *
	 * @var string
	 */
	private $assets_url;

	/**
	 * Constructor.
	 */
	public function __construct() {
		$this->version    = defined( 'GEODIRECTORY_VERSION' ) ? GEODIRECTORY_VERSION : '3.0.0';

		// Navigate up from src/Common/ to plugin root, then into assets/
		$this->assets_url = GEODIRECTORY_PLUGIN_URL . '/assets/';
	}

	/**
	 * Register hooks for asset management.
	 */
	public function register(): void {
		add_action( 'wp_enqueue_scripts', [ $this, 'register_frontend_scripts' ] );
		add_action( 'admin_enqueue_scripts', [ $this, 'register_admin_scripts' ] );
	}

	/**
	 * Register and Enqueue Frontend Scripts & Styles.
	 */
	public function register_frontend_scripts() {
		// 1. Frontend Styles (Compiled from resources/styles/frontend.scss)
		wp_enqueue_style(
			'geodir-frontend',
			$this->assets_url . 'css/geodir-frontend-styles.css',
			[], // Dependencies (Bootstrap handled externally)
			$this->version
		);

		// 2. Frontend Scripts
		// Note: We assume AlpineJS is loaded externally via Composer/Theme.
		wp_enqueue_script(
			'geodir-frontend',
			$this->assets_url . 'js/geodir-frontend.js',
			[], // No jQuery dependency for v3 frontend
			$this->version,
			true // Load in footer
		);

		// 3. Map Handler (Registered only, not enqueued globaly)
		// Use Assets::enqueue_map_assets() to load this when needed.
		wp_register_script(
			'geodir-map-handler',
			$this->assets_url . 'js/geodir-map-handler.js',
			[ 'geodir-frontend' ],
			$this->version,
			true
		);
	}

	/**
	 * Register and Enqueue Admin Scripts & Styles.
	 */
	public function register_admin_scripts() {
		// Selective Enqueue: Only load on GeoDirectory screens
		if ( ! $this->should_load_admin_assets() ) {
			return;
		}

		// 1. Admin CSS
		wp_enqueue_style(
			'geodir-admin',
			$this->assets_url . 'css/geodir-admin-styles.css',
			[],
			$this->version
		);

		// 2. Admin JS
		wp_enqueue_script(
			'geodir-admin',
			$this->assets_url . 'js/geodir-admin.js',
			[ 'jquery' ], // Admin interfaces often still rely on WP Core jQuery
			$this->version,
			true
		);
	}

	/**
	 * Helper to conditionally enqueue map assets.
	 *
	 * @param string $provider 'google' or 'osm'
	 */
	public static function enqueue_map_assets( $provider = 'google' ) {
		wp_enqueue_script( 'geodir-map-handler' );

		// If specific provider libraries (like Google Maps API) need separate loading, do it here.
		// For now, we assume the handler manages the logic or the library is loaded elsewhere.
	}

	/**
	 * Check if the current admin screen is related to GeoDirectory.
	 *
	 * @return bool
	 */
	private function should_load_admin_assets() {
		$screen    = get_current_screen();
		$screen_id = $screen ? $screen->id : '';

		// Check for explicit GeoDirectory pages
		if ( strpos( $screen_id, 'geodirectory' ) !== false ) {
			return true;
		}

		// Check for GeoDirectory Custom Post Types (starts with gd_)
		if ( $screen && strpos( $screen->post_type, 'gd_' ) === 0 ) {
			return true;
		}

		return false;
	}
}
